[[constraint]]
  branch = "master"
  name = "github.com/RichardKnop/go-fixtures"

[[constraint]]
  branch = "master"
  name = "github.com/RichardKnop/jsonhal"

[[constraint]]
  branch = "master"
  name = "github.com/RichardKnop/logging"

[[constraint]]
  branch = "master"
  name = "github.com/RichardKnop/uuid"

[[constraint]]
  version = "3.2.9"
  name = "github.com/coreos/etcd"

[[constraint]]
  branch = "master"
  name = "github.com/gorilla/context"

[[constraint]]
  branch = "master"
  name = "github.com/gorilla/mux"

[[constraint]]
  branch = "master"
  name = "github.com/gorilla/sessions"

[[constraint]]
  version = "0.9.3"
  name = "github.com/hashicorp/consul"

[[constraint]]
  branch = "master"
  name = "github.com/jinzhu/gorm"

[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"

[[constraint]]
  version = "1.2.0"
  name = "github.com/mattn/go-sqlite3"

[[constraint]]
  branch = "master"
  name = "github.com/oxtoacart/bpool"

[[constraint]]
  branch = "master"
  name = "github.com/phyber/negroni-gzip"

[[constraint]]
  branch = "master"
  name = "github.com/stretchr/testify"

[[constraint]]
  branch = "master"
  name = "github.com/unrolled/secure"

[[constraint]]
  branch = "master"
  name = "github.com/urfave/cli"

[[constraint]]
  branch = "master"
  name = "github.com/urfave/negroni"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  version = "1.2.15"
  name = "gopkg.in/tylerb/graceful.v1"

[[override]]
  version = "~1.5.0"
  name = "google.golang.org/grpc"
